test-name: train-data
ocr-system: paddleocr
augmentation: False

# task to execute
tasks:
    det: y
    rec: y

# dictionary to use and number of workers
dict: ./dict/en_dict.txt
workers: 8

# list of dataset to select
datasets:
    cord:
    funsd: y
    gnhk:
    iam:
    sroie:
    xfund:
        xfund-de:
        xfund-es:
        xfund-fr:
        xfund-it:
        xfund-ja:
        xfund-pt:
        xfund-zh:
    wildreceipt: