augmentation_params:
    blurring:
        enabled: true
        type: "gaussian"  # options: "gaussian", "box", "median", "motion"
        probability: 0.5
        params:
            gaussian:
                max_radius: 2.0
            box:
                max_radius: 2
            median:
                max_kernel_size: 3
            motion:
                max_kernel_size: 5
                angle: 0