# test name
test-name: train-data
ocr-system: paddleocr

# task to execute
tasks:
    det: n
    rec: n

# list of dataset to select
datasets:
    - funsd: n
    - iam: n
    - sroie: n
    - xfund:
        xfund-de: y
        xfund-es: n
        xfund-fr: n
        xfund-it: n
        xfund-ja: n
        xfund-pt: n
        xfund-zh: n

# augmentation settings
augmentation:
    - skewing:
    - distortion:
    - blurring: