# test name
test-name: train-data
ocr-system: doctr

# task to execute
tasks:
    det: y
    rec: y

dict: ./dict/en_dict.txt

# list of dataset to select
datasets:
    funsd: y
    gnhk: n
    iam: n
    sroie: n
    xfund:
        xfund-de: n
        xfund-es: n
        xfund-fr: n
        xfund-it: n
        xfund-ja: n
        xfund-pt: n
        xfund-zh: n